import { Ionicons } from '@expo/vector-icons';
import * as Location from 'expo-location';
import { StatusBar } from 'expo-status-bar';
import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button,Card,Field } from './src/components/Ui';
import { TripSummary } from './src/components/TripSummary';
import { reverseGeocode,searchPlace } from './src/services/geocoding';
import { getCurrentWeather } from './src/services/weather';
import { colors,spacing } from './src/theme';
import type { Place,Trip } from './src/types';
import { haversineKm } from './src/utils/distance';

export default function App(){const [originText,setOriginText]=useState('');const [destinationText,setDestinationText]=useState('');const [currentOrigin,setCurrentOrigin]=useState<Place>();const [locationLoading,setLocationLoading]=useState(false);const [tripLoading,setTripLoading]=useState(false);const [trip,setTrip]=useState<Trip>();
async function useLocation(){setLocationLoading(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){Alert.alert('Localização não permitida','Sem problemas: digite sua origem manualmente.');return}const position=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const place=await reverseGeocode(position.coords.latitude,position.coords.longitude);setCurrentOrigin(place);setOriginText('Minha localização atual')}catch{Alert.alert('Localização indisponível','Não conseguimos obter sua localização. Digite a origem manualmente.')}finally{setLocationLoading(false)}}
async function prepare(){if(!originText.trim()||!destinationText.trim()){Alert.alert('Complete a viagem','Informe a origem e o destino para continuar.');return}setTripLoading(true);setTrip(undefined);try{const origin=currentOrigin&&originText==='Minha localização atual'?currentOrigin:await searchPlace(originText.trim());const destination=await searchPlace(destinationText.trim());const [originWeather,destinationWeather]=await Promise.all([getCurrentWeather(origin),getCurrentWeather(destination)]);setTrip({origin,destination,distanceKm:haversineKm(origin,destination),originWeather,destinationWeather})}catch(error){Alert.alert('Não foi possível preparar a viagem',error instanceof Error?error.message:'Tente novamente em instantes.')}finally{setTripLoading(false)}}
return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.brand}><View><Text style={styles.logo}>Vora<Text style={styles.dot}>.</Text></Text><Text style={styles.tagline}>Saiba antes de sair.</Text></View><View style={styles.logoIcon}><Ionicons name="navigate" size={24} color="#fff"/></View></View><View style={styles.intro}><Text style={styles.title}>Prepare seu próximo deslocamento</Text><Text style={styles.subtitle}>Origem, destino e clima reunidos antes de você sair.</Text></View><Card><Field label="De onde você sai?" value={originText} onChangeText={v=>{setOriginText(v);setCurrentOrigin(undefined)}} placeholder="Digite sua origem" icon="radio-button-on-outline"/><Button title="Usar minha localização atual" icon="locate-outline" secondary loading={locationLoading} onPress={useLocation}/><Field label="Para onde você vai?" value={destinationText} onChangeText={setDestinationText} placeholder="Digite seu destino" icon="location-outline"/><Button title="Preparar viagem" icon="arrow-forward" loading={tripLoading} onPress={prepare}/></Card>{trip&&<TripSummary trip={trip}/>}<Card><View style={styles.recentHeader}><View style={styles.recentIcon}><Ionicons name="time-outline" size={22} color={colors.primary}/></View><View><Text style={styles.recentTitle}>Rotas recentes</Text><Text style={styles.recentSubtitle}>Acesso rápido aos seus trajetos</Text></View></View><View style={styles.empty}><Text style={styles.emptyTitle}>Ainda não há viagens por aqui</Text><Text style={styles.emptyText}>Suas viagens frequentes aparecerão aqui.</Text></View></Card><Text style={styles.footer}>Vora · informações para decidir antes de navegar</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},flex:{flex:1},content:{padding:spacing.lg,paddingBottom:48,gap:spacing.lg,maxWidth:680,width:'100%',alignSelf:'center'},brand:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{fontSize:34,fontWeight:'900',letterSpacing:-1.5,color:colors.primary},dot:{color:colors.accent},tagline:{color:colors.muted,fontSize:14,fontWeight:'600'},logoIcon:{width:46,height:46,borderRadius:16,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},intro:{marginTop:spacing.sm},title:{fontSize:28,fontWeight:'900',letterSpacing:-.5,lineHeight:34,color:colors.text},subtitle:{fontSize:16,lineHeight:23,color:colors.muted,marginTop:spacing.sm},recentHeader:{flexDirection:'row',alignItems:'center',gap:spacing.md},recentIcon:{width:42,height:42,borderRadius:14,backgroundColor:colors.primaryLight,alignItems:'center',justifyContent:'center'},recentTitle:{fontWeight:'900',fontSize:17,color:colors.text},recentSubtitle:{fontSize:12,color:colors.muted,marginTop:2},empty:{paddingVertical:spacing.lg,alignItems:'center',borderTopWidth:1,borderTopColor:colors.border},emptyTitle:{fontWeight:'700',color:colors.text},emptyText:{color:colors.muted,fontSize:13,marginTop:spacing.xs},footer:{textAlign:'center',fontSize:12,color:colors.muted}});
