import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing } from '../theme';
import type { FavoriteRoute, SavedPlace, SavedPlaceLabel } from '../types';
import { addressParts } from '../utils/address';
import { Card } from './Ui';
import { RouteIllustration, type RouteScene } from './Illustrations';

const routeScenes: RouteScene[] = ['beach', 'city', 'home', 'bridge', 'road'];

export function SavedPlacesSection({ places, onPress, onDelete }: { places: SavedPlace[]; onPress: (label: SavedPlaceLabel) => void; onDelete: (label: SavedPlaceLabel) => void }) {
  return <Card><Text style={styles.heading}>Meus lugares</Text><View style={styles.places}>{(['Casa', 'Trabalho'] as const).map((label) => { const place = places.find((item) => item.label === label); return <Pressable key={label} style={styles.place} onPress={() => onPress(label)}><View style={[styles.placeIcon, label === 'Trabalho' && styles.work]}><Ionicons name={label === 'Casa' ? 'home' : 'briefcase'} size={22} color="#fff"/></View><View style={styles.copy}><Text style={styles.itemTitle}>{label}</Text><Text numberOfLines={1} style={styles.itemSubtitle}>{place ? addressParts(place.name).title : `Salvar ${label.toLowerCase()}`}</Text></View>{place && <Pressable accessibilityLabel={`Excluir ${label}`} hitSlop={10} onPress={() => onDelete(label)}><Ionicons name="trash-outline" size={17} color={colors.muted}/></Pressable>}<Ionicons name="chevron-forward" size={20} color={colors.primary}/></Pressable>})}</View></Card>;
}

export function FavoriteRoutesSection({ routes, onPress, onDelete }: { routes: FavoriteRoute[]; onPress: (route: FavoriteRoute) => void; onDelete: (id: string) => void }) {
  return <Card><View style={styles.headingRow}><Text style={styles.heading}>Rotas favoritas</Text><Ionicons name="star" size={21} color={colors.accent}/></View>{routes.length === 0 ? <View style={styles.empty}><Ionicons name="star-outline" size={28} color={colors.accent}/><Text style={styles.itemSubtitle}>Suas viagens salvas aparecerão aqui.</Text></View> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.routes}>{routes.map((route, index) => { const from = addressParts(route.origin.name); const to = addressParts(route.destination.name); return <Pressable key={route.id} style={styles.route} onPress={() => onPress(route)}><View style={styles.artWrap}><RouteIllustration scene={routeScenes[index % routeScenes.length]!}/><Pressable accessibilityLabel="Excluir rota" hitSlop={8} style={styles.routeStar} onPress={() => onDelete(route.id)}><Ionicons name="star" size={16} color={colors.accent}/></Pressable></View><Text numberOfLines={1} style={styles.routeTitle}>{from.subtitle || from.title}</Text><Ionicons name="arrow-down" size={12} color={colors.primary}/><Text numberOfLines={1} style={styles.routeTitle}>{to.subtitle || to.title}</Text></Pressable>})}</ScrollView>}</Card>;
}
const styles = StyleSheet.create({ heading: { fontSize: 17, fontWeight: '900', color: colors.text }, headingRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, places: { gap: 7 }, place: { flexDirection: 'row', minHeight: 62, alignItems: 'center', padding: 8, borderRadius: radius.md, backgroundColor: colors.input, gap: spacing.sm }, placeIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.orange }, work: { backgroundColor: colors.blue }, copy: { flex: 1 }, itemTitle: { color: colors.text, fontWeight: '800', fontSize: 13 }, itemSubtitle: { color: colors.muted, fontSize: 11, marginTop: 2 }, empty: { alignItems: 'center', paddingVertical: spacing.lg, gap: spacing.sm }, routes: { gap: spacing.sm, paddingRight: spacing.sm }, route: { width: 118 }, artWrap: { height: 90, borderRadius: radius.md, overflow: 'hidden', marginBottom: 6 }, routeArt: { width: '100%', height: '100%' }, routeStar: { position: 'absolute', right: 5, top: 5, width: 26, height: 26, backgroundColor: '#fff', borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, routeTitle: { color: colors.text, fontSize: 10, fontWeight: '800', marginVertical: 1 } });
