import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing } from '../theme';
import type { FavoriteRoute, SavedPlace, SavedPlaceLabel } from '../types';
import { addressParts } from '../utils/address';
import { Card } from './Ui';

export function SavedPlacesSection({ places, onPress, onDelete }: { places: SavedPlace[]; onPress: (label: SavedPlaceLabel) => void; onDelete: (label: SavedPlaceLabel) => void }) {
  return <Card><Text style={styles.heading}>Meus lugares</Text><View style={styles.places}>{(['Casa', 'Trabalho'] as const).map((label) => { const place = places.find((item) => item.label === label); return <Pressable key={label} style={styles.place} onPress={() => onPress(label)}><View style={[styles.placeIcon, label === 'Trabalho' && styles.work]}><Ionicons name={label === 'Casa' ? 'home' : 'briefcase'} size={22} color="#fff"/></View><View style={styles.copy}><Text style={styles.itemTitle}>{label}</Text><Text numberOfLines={1} style={styles.itemSubtitle}>{place ? addressParts(place.name).title : `Salvar ${label.toLowerCase()}`}</Text></View>{place && <Pressable accessibilityLabel={`Excluir ${label}`} hitSlop={10} onPress={() => onDelete(label)}><Ionicons name="trash-outline" size={17} color={colors.muted}/></Pressable>}<Ionicons name="chevron-forward" size={20} color={colors.primary}/></Pressable>})}</View></Card>;
}

export function FavoriteRoutesSection({ routes, onPress, onDelete }: { routes: FavoriteRoute[]; onPress: (route: FavoriteRoute) => void; onDelete: (id: string) => void }) {
  return <Card><View style={styles.headingRow}><Text style={styles.heading}>Rotas favoritas</Text><Ionicons name="star" size={21} color={colors.accent}/></View>{routes.length === 0 ? <View style={styles.empty}><Ionicons name="star-outline" size={28} color={colors.accent}/><Text style={styles.itemSubtitle}>Suas viagens salvas aparecerão aqui.</Text></View> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.routes}>{routes.map((route, index) => { const from = addressParts(route.origin.name); const to = addressParts(route.destination.name); return <Pressable key={route.id} style={[styles.route, { backgroundColor: index % 2 ? '#DDF0EC' : '#FFF0C9' }]} onPress={() => onPress(route)}><View style={styles.routeTop}><Text style={styles.routeEmoji}>{index % 3 === 0 ? '🏝️' : index % 3 === 1 ? '🏙️' : '🏡'}</Text><Pressable accessibilityLabel="Excluir rota" hitSlop={8} style={styles.routeStar} onPress={() => onDelete(route.id)}><Ionicons name="star" size={18} color={colors.accent}/></Pressable></View><Text numberOfLines={1} style={styles.routeTitle}>{from.title}</Text><Ionicons name="arrow-down" size={13} color={colors.primary}/><Text numberOfLines={1} style={styles.routeTitle}>{to.title}</Text></Pressable>})}</ScrollView>}</Card>;
}
const styles = StyleSheet.create({ heading: { fontSize: 18, fontWeight: '900', color: colors.text }, headingRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, places: { gap: spacing.sm }, place: { flexDirection: 'row', minHeight: 70, alignItems: 'center', padding: spacing.sm, borderRadius: radius.md, backgroundColor: colors.input, gap: spacing.sm }, placeIcon: { width: 43, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.orange }, work: { backgroundColor: colors.blue }, copy: { flex: 1 }, itemTitle: { color: colors.text, fontWeight: '800', fontSize: 14 }, itemSubtitle: { color: colors.muted, fontSize: 12, marginTop: 3 }, empty: { alignItems: 'center', paddingVertical: spacing.lg, gap: spacing.sm }, routes: { gap: spacing.sm, paddingRight: spacing.sm }, route: { width: 126, minHeight: 145, borderRadius: radius.md, padding: spacing.sm, justifyContent: 'flex-end', overflow: 'hidden' }, routeTop: { flex: 1, flexDirection: 'row', justifyContent: 'space-between' }, routeEmoji: { fontSize: 37 }, routeStar: { width: 28, height: 28, backgroundColor: '#fff', borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, routeTitle: { color: colors.text, fontSize: 11, fontWeight: '800', marginVertical: 2 } });
