import { Ionicons } from '@expo/vector-icons';
import { Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import type { Trip, Weather } from '../types';
import { colors, radius, spacing } from '../theme';
import { addressParts } from '../utils/address';
import { googleMapsUrl } from '../utils/maps';
import { Button, Card } from './Ui';

const weatherEmoji = (code: number) => code === 0 ? '☀️' : code <= 2 ? '🌤️' : code <= 48 ? '☁️' : code >= 95 ? '⛈️' : code >= 71 && code <= 75 ? '❄️' : '🌧️';
function Stop({ name, destination = false }: { name: string; destination?: boolean }) {
  const place = addressParts(name);
  return <View style={styles.stop}><View style={[styles.stopIcon, destination && styles.destination]}><Ionicons name={destination ? 'location' : 'ellipse'} size={destination ? 15 : 8} color="#fff"/></View><View style={styles.stopCopy}><Text numberOfLines={1} style={styles.stopTitle}>{place.title}</Text>{!!place.subtitle && <Text numberOfLines={1} style={styles.stopSubtitle}>{place.subtitle}</Text>}</View></View>;
}
function WeatherCard({ title, weather }: { title: string; weather: Weather }) {
  return <View style={styles.weather}><Text style={styles.weatherTitle}>{title}</Text><View style={styles.weatherMain}><Text style={styles.weatherEmoji}>{weatherEmoji(weather.weatherCode)}</Text><Text style={styles.temperature}>{weather.temperature}°</Text></View><Text numberOfLines={2} style={styles.condition}>{weather.description}</Text><View style={styles.metrics}><Text style={styles.detail}>💧 {weather.precipitationProbability}%</Text><Text style={styles.detail}>Sensação {weather.apparentTemperature}°</Text></View></View>;
}
export function TripSummary({ trip, onSave, isFavorite }: { trip: Trip; onSave: () => void; isFavorite: boolean }) {
  const rain = trip.destinationWeather.precipitationProbability >= 40;
  return <View style={styles.wrap}><Card><Text style={styles.heading}>Sua viagem</Text><View style={styles.summary}><View style={styles.stops}><Stop name={trip.origin.name}/><View style={styles.dotted}/><Stop name={trip.destination.name} destination/></View><View style={styles.distanceBox}><Text style={styles.distance}>{trip.distanceKm.toFixed(0)}</Text><Text style={styles.km}>km</Text><Text style={styles.line}>linha reta ⓘ</Text></View></View><Text style={styles.estimate}>Estimativa geográfica; a distância rodoviária pode variar.</Text></Card>
    <View style={styles.weatherRow}><WeatherCard title="Na saída" weather={trip.originWeather}/><WeatherCard title="No destino" weather={trip.destinationWeather}/></View>
    {rain && <View style={styles.warning}><Text style={styles.warningEmoji}>🌧️</Text><View style={{ flex: 1 }}><Text style={styles.warningTitle}>Leve o guarda-chuva</Text><Text style={styles.warningBody}>Há possibilidade de chuva no destino.</Text></View></View>}
    <Card style={styles.actions}><Pressable style={[styles.save, isFavorite && styles.saved]} onPress={onSave}><Ionicons name={isFavorite ? 'star' : 'star-outline'} size={24} color={colors.accent}/><Text style={styles.saveText}>{isFavorite ? 'Rota favoritada' : 'Salvar rota'}</Text></Pressable><Button title="Abrir rota no Google Maps" icon="open-outline" onPress={() => Linking.openURL(googleMapsUrl(trip))}/></Card>
  </View>;
}
const styles = StyleSheet.create({ wrap: { gap: spacing.md }, heading: { fontSize: 18, fontWeight: '900', color: colors.text }, summary: { flexDirection: 'row', alignItems: 'stretch' }, stops: { flex: 1, paddingRight: spacing.sm }, stop: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, minHeight: 42 }, stopIcon: { width: 18, height: 18, borderRadius: 9, backgroundColor: colors.turquoise, alignItems: 'center', justifyContent: 'center' }, destination: { backgroundColor: colors.orange }, stopCopy: { flex: 1 }, stopTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, stopSubtitle: { color: colors.muted, fontSize: 12, marginTop: 2 }, dotted: { height: 23, borderLeftWidth: 2, borderStyle: 'dashed', borderColor: '#7A9692', marginLeft: 8 }, distanceBox: { width: 100, borderLeftWidth: 1, borderLeftColor: colors.border, alignItems: 'center', justifyContent: 'center', paddingLeft: spacing.sm }, distance: { fontSize: 42, lineHeight: 44, fontWeight: '900', color: colors.primary }, km: { color: colors.primary, fontWeight: '900' }, line: { color: colors.muted, fontSize: 11, marginTop: spacing.sm }, estimate: { fontSize: 11, color: colors.muted }, weatherRow: { flexDirection: 'row', gap: spacing.sm }, weather: { flex: 1, minWidth: 0, borderRadius: radius.lg, backgroundColor: colors.surface, padding: spacing.md, shadowColor: '#765218', shadowOpacity: .1, shadowRadius: 12, elevation: 3 }, weatherTitle: { fontWeight: '900', color: colors.text }, weatherMain: { flexDirection: 'row', alignItems: 'center', marginVertical: spacing.sm }, weatherEmoji: { fontSize: 37 }, temperature: { fontSize: 29, color: colors.text, fontWeight: '900', marginLeft: 3 }, condition: { color: colors.text, fontSize: 12, minHeight: 32 }, metrics: { marginTop: spacing.sm, gap: 3 }, detail: { color: colors.muted, fontSize: 10 }, warning: { borderRadius: radius.md, padding: spacing.md, backgroundColor: colors.warning, flexDirection: 'row', gap: spacing.sm }, warningEmoji: { fontSize: 24 }, warningTitle: { fontWeight: '900', color: colors.warningText }, warningBody: { color: colors.warningText, fontSize: 12, marginTop: 2 }, actions: { padding: spacing.md }, save: { minHeight: 56, borderRadius: radius.md, backgroundColor: '#FFE9B2', flexDirection: 'row', gap: spacing.sm, alignItems: 'center', justifyContent: 'center' }, saved: { backgroundColor: '#FFDEA0', borderWidth: 1, borderColor: colors.accent }, saveText: { color: colors.text, fontSize: 16, fontWeight: '900' } });
