import { Ionicons } from '@expo/vector-icons';
import { Linking, StyleSheet, Text, View } from 'react-native';
import type { Trip,Weather } from '../types';
import { colors, radius, spacing } from '../theme';
import { googleMapsUrl } from '../utils/maps';
import { Button,Card } from './Ui';
const short=(name:string)=>name.split(',').slice(0,2).join(',');
function WeatherRow({title,weather,apparent=false}:{title:string;weather:Weather;apparent?:boolean}){return <View style={styles.weather}><View style={styles.weatherIcon}><Ionicons name={weather.icon as never} size={25} color={colors.primary}/></View><View style={styles.weatherText}><Text style={styles.weatherTitle}>{title}</Text><Text style={styles.condition}>{weather.temperature}°C · {weather.description}</Text><Text style={styles.detail}>{weather.precipitationProbability}% de chance de chuva{apparent?` · sensação de ${weather.apparentTemperature}°C`:''}</Text></View></View>}
export function TripSummary({trip}:{trip:Trip}){const rain=trip.destinationWeather.precipitationProbability>=40;return <Card><View><Text style={styles.eyebrow}>SUA VIAGEM</Text><Text style={styles.route}>{short(trip.origin.name)} <Text style={styles.arrow}>→</Text> {short(trip.destination.name)}</Text></View><View><Text style={styles.distance}>{trip.distanceKm.toFixed(0)} km</Text><Text style={styles.estimate}>Estimativa em linha reta · não é distância rodoviária</Text></View><View style={styles.divider}/><WeatherRow title="Na saída" weather={trip.originWeather} apparent/><WeatherRow title="No destino" weather={trip.destinationWeather}/>{rain&&<View style={styles.warning}><Ionicons name="warning-outline" size={23} color={colors.warningText}/><View style={{flex:1}}><Text style={styles.warningTitle}>Atenção</Text><Text style={styles.warningBody}>Existe possibilidade de chuva no destino.</Text></View></View>}<Button title="Abrir rota no Google Maps" icon="open-outline" onPress={()=>Linking.openURL(googleMapsUrl(trip))}/></Card>}
const styles=StyleSheet.create({eyebrow:{fontSize:12,fontWeight:'800',letterSpacing:1.4,color:colors.muted,marginBottom:spacing.xs},route:{fontSize:21,fontWeight:'800',lineHeight:29,color:colors.text},arrow:{color:colors.accent},distance:{fontSize:34,fontWeight:'900',color:colors.primary},estimate:{fontSize:12,color:colors.muted,marginTop:2},divider:{height:1,backgroundColor:colors.border},weather:{flexDirection:'row',alignItems:'center',gap:spacing.md},weatherIcon:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:colors.primaryLight},weatherText:{flex:1},weatherTitle:{fontWeight:'800',fontSize:15,color:colors.text},condition:{fontSize:15,color:colors.text,marginTop:2},detail:{fontSize:12,color:colors.muted,marginTop:2},warning:{borderRadius:radius.md,padding:spacing.md,backgroundColor:colors.warning,flexDirection:'row',gap:spacing.sm},warningTitle:{fontWeight:'900',color:colors.warningText},warningBody:{color:colors.warningText,marginTop:2,lineHeight:19}});
