import { Ionicons } from '@expo/vector-icons';
import { Linking, Pressable, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import type { Trip, Weather } from '../types';
import { colors, radius, spacing } from '../theme';
import { addressParts } from '../utils/address';
import { googleMapsUrl, mapsButtonLabel } from '../utils/maps';
import { Button, Card } from './Ui';
import { WeatherIllustration, type WeatherScene } from './Illustrations';

function weatherScene(code: number): WeatherScene { return code === 0 ? 'sunny' : code <= 2 ? 'partly' : code <= 48 ? 'cloudy' : code >= 95 ? 'storm' : 'rainy'; }
const formatDistance = (meters: number) => new Intl.NumberFormat('pt-BR', { maximumFractionDigits: meters < 10000 ? 1 : 0 }).format(meters / 1000);
function formatDuration(seconds: number) { const minutes = Math.round(seconds / 60); const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? `~${hours}h${rest ? ` ${String(rest).padStart(2, '0')}min` : ''} de carro` : `~${minutes}min de carro`; }
function Stop({ name, destination = false }: { name: string; destination?: boolean }) { const place = addressParts(name); return <View style={styles.stop}><View style={[styles.stopIcon, destination && styles.destination]}><Ionicons name={destination ? 'location' : 'ellipse'} size={destination ? 15 : 8} color="#fff"/></View><View style={styles.stopCopy}><Text numberOfLines={1} ellipsizeMode="tail" style={styles.stopTitle}>{place.title}</Text>{!!place.subtitle && <Text numberOfLines={1} ellipsizeMode="tail" style={styles.stopSubtitle}>{place.subtitle}</Text>}</View></View>; }
function WeatherCard({ title, weather, compact }: { title: string; weather: Weather; compact: boolean }) { return <View style={[styles.weather, compact && styles.weatherCompact]}><Text numberOfLines={1} style={styles.weatherTitle}>{title}</Text><View style={styles.weatherMain}><View style={[styles.artBox, compact && styles.artBoxCompact]}><WeatherIllustration type={weatherScene(weather.weatherCode)}/></View><View style={styles.weatherCopy}><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.75} style={styles.temperature}>{weather.temperature}°C</Text><Text numberOfLines={2} style={styles.condition}>{weather.description}</Text></View></View><View style={styles.metrics}><View style={styles.metric}><Ionicons name="water" size={13} color={colors.blue}/><Text numberOfLines={1} style={styles.detail}>{weather.precipitationProbability}%</Text></View><View style={styles.metricDivider}/><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.72} style={styles.feels}>Sensação {weather.apparentTemperature}°C</Text></View></View>; }
export function TripSummary({ trip, onSave, isFavorite }: { trip: Trip; onSave: () => void; isFavorite: boolean }) { const rain=trip.destinationWeather.precipitationProbability>=40; const compact=useWindowDimensions().width<390; return <View style={styles.wrap}><Card><Text style={styles.heading}>Sua viagem</Text><View style={styles.summary}><View style={styles.stops}><Stop name={trip.origin.name}/><View style={styles.dotted}/><Stop name={trip.destination.name} destination/></View><View style={[styles.distanceBox,compact&&styles.distanceCompact]}><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.55} style={styles.distance}>{formatDistance(trip.routeEstimate.distanceMeters)}</Text><Text style={styles.km}>km</Text><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={.7} style={styles.duration}>{formatDuration(trip.routeEstimate.durationSeconds)}</Text></View></View><Text style={styles.estimate}>Distância rodoviária de referência.</Text></Card><View style={styles.weatherRow}><WeatherCard compact={compact} title="Na saída" weather={trip.originWeather}/><WeatherCard compact={compact} title="No destino" weather={trip.destinationWeather}/></View>{rain&&<View style={styles.warning}><Ionicons name="rainy" size={24} color={colors.blue}/><View style={styles.warningCopy}><Text style={styles.warningTitle}>Leve o guarda-chuva</Text><Text style={styles.warningBody}>Há possibilidade de chuva no destino.</Text></View></View>}<Card style={styles.actions}><Pressable style={[styles.save,isFavorite&&styles.saved]} onPress={onSave}><Ionicons name={isFavorite?'star':'star-outline'} size={24} color={colors.accent}/><Text style={styles.saveText}>{isFavorite?'Rota favoritada':'Salvar rota'}</Text></Pressable><Button title={mapsButtonLabel[trip.mode]} icon="open-outline" onPress={()=>Linking.openURL(googleMapsUrl(trip))}/></Card></View>; }
const styles=StyleSheet.create({wrap:{gap:spacing.sm},heading:{fontSize:16,fontWeight:'900',color:colors.text},summary:{flexDirection:'row',alignItems:'stretch'},stops:{flex:1,minWidth:0,paddingRight:spacing.sm},stop:{flexDirection:'row',alignItems:'center',gap:spacing.sm,minHeight:38},stopIcon:{width:18,height:18,borderRadius:9,backgroundColor:colors.turquoise,alignItems:'center',justifyContent:'center'},destination:{backgroundColor:colors.orange},stopCopy:{flex:1,minWidth:0},stopTitle:{color:colors.text,fontSize:13,fontWeight:'800'},stopSubtitle:{color:colors.muted,fontSize:11,marginTop:1},dotted:{height:18,borderLeftWidth:2,borderStyle:'dashed',borderColor:'#7A9692',marginLeft:8},distanceBox:{width:126,minWidth:112,borderLeftWidth:1,borderLeftColor:colors.border,alignItems:'center',justifyContent:'center',paddingLeft:spacing.sm},distanceCompact:{width:110,minWidth:102},distance:{width:'100%',textAlign:'center',fontSize:38,lineHeight:42,fontWeight:'900',color:colors.primary},km:{color:colors.primary,fontWeight:'900'},duration:{width:'100%',textAlign:'center',color:colors.muted,fontSize:10,marginTop:4},estimate:{fontSize:10,color:colors.muted},weatherRow:{flexDirection:'row',gap:spacing.sm,alignItems:'stretch'},weather:{flex:1,minWidth:0,minHeight:145,borderRadius:radius.lg,backgroundColor:colors.surface,padding:spacing.md,shadowColor:'#765218',shadowOpacity:.1,shadowRadius:12,elevation:3},weatherCompact:{paddingHorizontal:10},weatherTitle:{fontSize:13,fontWeight:'900',color:colors.text},weatherMain:{flexDirection:'row',alignItems:'center',marginTop:4,minWidth:0},artBox:{width:62,height:62,alignItems:'center',justifyContent:'center'},artBoxCompact:{width:52,transform:[{scale:.86}]},weatherCopy:{flex:1,minWidth:0},temperature:{fontSize:23,color:colors.text,fontWeight:'900'},condition:{color:colors.text,fontSize:10,lineHeight:13,marginTop:2,minHeight:26},metrics:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.border,paddingTop:7,flexDirection:'row',alignItems:'center',gap:5},metric:{flexDirection:'row',alignItems:'center',gap:2},metricDivider:{height:18,width:1,backgroundColor:colors.border},detail:{color:colors.muted,fontSize:9},feels:{flex:1,textAlign:'right',color:colors.muted,fontSize:9},warning:{borderRadius:radius.md,padding:spacing.md,backgroundColor:colors.warning,flexDirection:'row',gap:spacing.sm},warningCopy:{flex:1},warningTitle:{fontWeight:'900',color:colors.warningText},warningBody:{color:colors.warningText,fontSize:12,marginTop:2},actions:{padding:spacing.sm},save:{minHeight:50,borderRadius:radius.md,backgroundColor:'#FFE9B2',borderWidth:1,borderColor:colors.accent,flexDirection:'row',gap:spacing.sm,alignItems:'center',justifyContent:'center'},saved:{backgroundColor:'#FFDEA0'},saveText:{color:colors.text,fontSize:16,fontWeight:'900'}});
