import { Ionicons } from '@expo/vector-icons';
import type { ComponentProps, ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius, spacing } from '../theme';

type IconName=ComponentProps<typeof Ionicons>['name'];
export function Card({children}: {children:ReactNode}){return <View style={styles.card}>{children}</View>}
export function Field({label,value,onChangeText,placeholder,icon}: {label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;icon:IconName}){return <View><Text style={styles.label}>{label}</Text><View style={styles.inputBox}><Ionicons name={icon} size={20} color={colors.muted}/><TextInput style={styles.input} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#89938F" autoCapitalize="words" returnKeyType="done"/></View></View>}
export function Button({title,onPress,loading=false,secondary=false,icon}: {title:string;onPress:()=>void;loading?:boolean;secondary?:boolean;icon?:IconName}){return <Pressable disabled={loading} onPress={onPress} style={({pressed})=>[styles.button,secondary&&styles.secondary,pressed&&styles.pressed]}>{loading?<ActivityIndicator color={secondary?colors.primary:'#fff'}/>:<><Text style={[styles.buttonText,secondary&&styles.secondaryText]}>{title}</Text>{icon&&<Ionicons name={icon} size={20} color={secondary?colors.primary:'#fff'}/>}</>}</Pressable>}
const styles=StyleSheet.create({card:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:spacing.lg,borderWidth:1,borderColor:colors.border,gap:spacing.md,shadowColor:'#1A3029',shadowOffset:{width:0,height:4},shadowOpacity:.06,shadowRadius:12,elevation:2},label:{fontSize:15,fontWeight:'700',color:colors.text,marginBottom:spacing.sm},inputBox:{height:54,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.input,flexDirection:'row',alignItems:'center',paddingHorizontal:spacing.md,gap:spacing.sm},input:{flex:1,fontSize:16,color:colors.text},button:{minHeight:54,borderRadius:radius.md,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:spacing.sm,paddingHorizontal:spacing.md},secondary:{backgroundColor:colors.primaryLight},buttonText:{fontSize:16,fontWeight:'800',color:'#fff'},secondaryText:{color:colors.primary},pressed:{opacity:.82}});
